version: '3.8'

services:
  shaggy-discord-bot:
    build: .
    container_name: shaggy-discord-bot
    restart: always
    env_file:
      - app.env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}

  redis:
    image: redis
    container_name: redis-shaggy-discord-bot
    restart: always
    ports:
      - "6389:6379"
    volumes:
      - /home/pc/docker-projects/shaggy-discord-bot/data:/root/redis
      - /home/pc/docker-projects/shaggy-discord-bot/redis.conf:/usr/local/etc/redis/redis.conf

